### ISSUE TITLE
Exception tracebacks are illegible

### ISSUE THREAD

**Issue by maxbane** [AllanChain/jupyterlab-theme-solarized-dark#25]
Thanks so much for creating this theme, I really love it. However, I noticed some room for improvement... when using a Python kernel, the way that tracebacks are rendered can make parts of them very difficult to read when using jupyterlab-theme-solarized-dark.

Steps to reproduce:

1. In a fresh venv: `pip install jupyterlab jupyterlab-theme-solarized-dark`
2. Start jupyterlab from the venv and set the Theme to JupyterLab Solarized Dark:
![Settings screenshot](https://i.imgur.com/MxEKYTo.png)
3. Create a notebook with a Python cell that raises an exception from a function body (for example):
![Exception screenshot](https://i.imgur.com/hEPnKpC.png)

Note how it is almost impossible to read to the yellow-highlighted source line in the second-to-last call frame of the traceback (line 4). That highlighting is from Jupyter, I have not edited the screenshot in any way! Also, while not quite as bad, the blue function names are pretty difficult to read as well.

**Comment by AllanChain** [comment]
Thanks for opening the issue! It definitely needs improvement and I will try to fix it this week.

**Comment by maxbane** [comment]
Thanks so much!

**Comment by AllanChain** [comment]
Oh, I forgot to mention that the blue text is not a easy fix because the style is inlined RGB. And since IPython outputs hard coded blue color into the console, it makes sense to respect it.
