### ISSUE TITLE
Wrong colors in jupyter-debugger extension

### ISSUE THREAD

**Issue by Rattge** [AllanChain/jupyterlab-theme-solarized-dark#3]
![image](https://user-images.githubusercontent.com/52904454/88460249-1be39400-cec5-11ea-83a9-35840ffc9433.png)
Hello.
I put screenshot only. If you need other info, let me know.

**Comment by AllanChain** [comment]
Having problem to install jupyter-debugger without conda, so just looked into source code. 

It's not my fault. They are not using css variables defined in the theme:

https://github.com/jupyterlab/debugger/blob/1866e9c47a2be651e4b57a15c4a20c4045bac228/src/panels/variables/grid.ts#L312-L330

**Comment by afshin** [comment]
Cheers @AllanChain and @zombba; this is definitely a bug in the debugger UI. Thanks for unearthing it!

**Comment by AllanChain** [comment]
Closing this issue. Follow jupyterlab/debugger issue for more info.
